name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  native-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
#          - windows-latest
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macOS-latest
            target: x86_64-apple-darwin
#          - os: windows-latest
#            target: i686-pc-windows-msvc
#          - os: windows-latest
#            target: x86_64-pc-windows-msvc
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          submodules: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-build-native-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=${{ matrix.target }}

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target=${{ matrix.target }}

      # Workaround for actions/cache#403 (https://github.com/actions/cache/issues/403)
      #
      # rust-lang/cargo#8603 has the exact bug that we run into
      # (https://github.com/rust-lang/cargo/issues/8603)
      - name: Flush the disk cache for macOS
        if: matrix.os == 'macos-latest'
        run: sudo /usr/sbin/purge

#  cross-checks:
#    needs: native-checks
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        include:
#          - target: aarch64-unknown-linux-gnu
#          - target: aarch64-unknown-linux-musl
#          - target: arm-unknown-linux-gnueabi
#          - target: arm-unknown-linux-gnueabihf
#          - target: arm-unknown-linux-musleabi
#          - target: arm-unknown-linux-musleabihf
#          - target: armv5te-unknown-linux-gnueabi
#          - target: armv5te-unknown-linux-musleabi
#          - target: armv7-unknown-linux-gnueabihf
#          - target: armv7-unknown-linux-musleabihf
#          - target: x86_64-unknown-linux-gnu
#          - target: x86_64-unknown-linux-musl
#    env:
#      RUST_BACKTRACE: 1
#
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v1
#        with:
#          submodules: true
#
#      - uses: actions/cache@v2
#        with:
#          path: |
#            ~/.cargo/registry
#            ~/.cargo/git
#            target
#          key: ${{ matrix.target }}-cargo-build-cross-${{ hashFiles('**/Cargo.lock') }}
#
#      - name: Build
#        uses: actions-rs/cargo@v1
#        with:
#          use-cross: true
#          command: build
#          args: --target=${{ matrix.target }}